// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Artist struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PlaybackEvent struct {
	ID            uuid.UUID      `json:"id"`
	TrackID       uuid.NullUUID  `json:"track_id"`
	UserID        uuid.NullUUID  `json:"user_id"`
	UserSessionID sql.NullString `json:"user_session_id"`
	PlayedAt      sql.NullTime   `json:"played_at"`
}

type Preset struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Data      string         `json:"data"`
	Mood      sql.NullString `json:"mood"`
	AuthorID  uuid.NullUUID  `json:"author_id"`
	IsBuiltin bool           `json:"is_builtin"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type PresetFavorite struct {
	UserID    uuid.UUID    `json:"user_id"`
	PresetID  uuid.UUID    `json:"preset_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	Revoked   bool         `json:"revoked"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Tag struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Track struct {
	ID            uuid.UUID       `json:"id"`
	UserID        uuid.UUID       `json:"user_id"`
	Title         string          `json:"title"`
	ArtistID      uuid.NullUUID   `json:"artist_id"`
	AudioFilePath string          `json:"audio_file_path"`
	DurationMs    int32           `json:"duration_ms"`
	FileHash      string          `json:"file_hash"`
	Mood          sql.NullString  `json:"mood"`
	Bpm           sql.NullFloat64 `json:"bpm"`
	Energy        sql.NullFloat64 `json:"energy"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
}

type TrackTag struct {
	TrackID   uuid.UUID    `json:"track_id"`
	TagID     uuid.UUID    `json:"tag_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type UploadSession struct {
	ID        uuid.UUID     `json:"id"`
	Status    string        `json:"status"`
	TrackID   uuid.NullUUID `json:"track_id"`
	UserID    uuid.NullUUID `json:"user_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	DisplayName  string       `json:"display_name"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
