// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ============================================================
	// PRESET FAVORITES
	// ============================================================
	AddPresetFavorite(ctx context.Context, arg AddPresetFavoriteParams) error
	// ============================================================
	// TRACK_TAGS (many-to-many)
	// ============================================================
	AssignTagToTrack(ctx context.Context, arg AssignTagToTrackParams) error
	CountPlaybacksForTrack(ctx context.Context, trackID uuid.NullUUID) (int64, error)
	CountTracksByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	// ============================================================
	// ARTISTS
	// ============================================================
	CreateArtist(ctx context.Context, name string) (Artist, error)
	// ============================================================
	// PLAYBACK EVENTS (analytics)
	// ============================================================
	CreatePlaybackEvent(ctx context.Context, arg CreatePlaybackEventParams) (PlaybackEvent, error)
	// ============================================================
	// PRESETS
	// ============================================================
	CreatePreset(ctx context.Context, arg CreatePresetParams) (Preset, error)
	// ============================================================
	// REFRESH TOKENS
	// ============================================================
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// ============================================================
	// TAGS
	// ============================================================
	CreateTag(ctx context.Context, name string) (Tag, error)
	// ============================================================
	// TRACKS
	// ============================================================
	CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error)
	// ============================================================
	// UPLOAD SESSIONS
	// ============================================================
	CreateUploadSession(ctx context.Context, status string) (UploadSession, error)
	// ============================================================
	// USERS
	// ============================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArtist(ctx context.Context, id uuid.UUID) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeletePreset(ctx context.Context, arg DeletePresetParams) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteTrack(ctx context.Context, id uuid.UUID) error
	GetArtist(ctx context.Context, id uuid.UUID) (Artist, error)
	GetArtistByName(ctx context.Context, name string) (Artist, error)
	// ============================================================
	// GALLERY (tag-driven grouping, user-scoped)
	// ============================================================
	GetGalleryTracksByUser(ctx context.Context, userID uuid.UUID) ([]GetGalleryTracksByUserRow, error)
	GetPreset(ctx context.Context, id uuid.UUID) (Preset, error)
	GetPresetFavorite(ctx context.Context, arg GetPresetFavoriteParams) (PresetFavorite, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTag(ctx context.Context, id uuid.UUID) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTrack(ctx context.Context, id uuid.UUID) (Track, error)
	GetTrackByFileHash(ctx context.Context, fileHash string) (Track, error)
	GetTrackByUser(ctx context.Context, arg GetTrackByUserParams) (Track, error)
	GetUploadSession(ctx context.Context, id uuid.UUID) (UploadSession, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListArtists(ctx context.Context) ([]Artist, error)
	ListPlaybackEventsForTrack(ctx context.Context, arg ListPlaybackEventsForTrackParams) ([]PlaybackEvent, error)
	ListPresets(ctx context.Context, arg ListPresetsParams) ([]ListPresetsRow, error)
	ListPresetsByMood(ctx context.Context, arg ListPresetsByMoodParams) ([]ListPresetsByMoodRow, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsForTrack(ctx context.Context, trackID uuid.UUID) ([]Tag, error)
	ListTagsWithTrackCount(ctx context.Context) ([]ListTagsWithTrackCountRow, error)
	ListTrackIDsByTag(ctx context.Context, tagID uuid.UUID) ([]uuid.UUID, error)
	ListTracksByTag(ctx context.Context, tagID uuid.UUID) ([]Track, error)
	ListTracksByUser(ctx context.Context, arg ListTracksByUserParams) ([]Track, error)
	ListUploadSessions(ctx context.Context, limit int32) ([]UploadSession, error)
	ListUserFavoritePresets(ctx context.Context, arg ListUserFavoritePresetsParams) ([]Preset, error)
	RemovePresetFavorite(ctx context.Context, arg RemovePresetFavoriteParams) error
	RemoveTagFromTrack(ctx context.Context, arg RemoveTagFromTrackParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateTrackMood(ctx context.Context, arg UpdateTrackMoodParams) (Track, error)
	UpdateUploadSessionStatus(ctx context.Context, arg UpdateUploadSessionStatusParams) (UploadSession, error)
}

var _ Querier = (*Queries)(nil)
