// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addPresetFavorite = `-- name: AddPresetFavorite :exec

INSERT INTO preset_favorites (user_id, preset_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPresetFavoriteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PresetID uuid.UUID `json:"preset_id"`
}

// ============================================================
// PRESET FAVORITES
// ============================================================
func (q *Queries) AddPresetFavorite(ctx context.Context, arg AddPresetFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addPresetFavorite, arg.UserID, arg.PresetID)
	return err
}

const assignTagToTrack = `-- name: AssignTagToTrack :exec

INSERT INTO track_tags (track_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignTagToTrackParams struct {
	TrackID uuid.UUID `json:"track_id"`
	TagID   uuid.UUID `json:"tag_id"`
}

// ============================================================
// TRACK_TAGS (many-to-many)
// ============================================================
func (q *Queries) AssignTagToTrack(ctx context.Context, arg AssignTagToTrackParams) error {
	_, err := q.db.ExecContext(ctx, assignTagToTrack, arg.TrackID, arg.TagID)
	return err
}

const countPlaybacksForTrack = `-- name: CountPlaybacksForTrack :one
SELECT count(*) FROM playback_events
WHERE track_id = $1
`

func (q *Queries) CountPlaybacksForTrack(ctx context.Context, trackID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaybacksForTrack, trackID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTracksByUser = `-- name: CountTracksByUser :one
SELECT count(*) FROM tracks WHERE user_id = $1
`

func (q *Queries) CountTracksByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTracksByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtist = `-- name: CreateArtist :one

INSERT INTO artists (name)
VALUES ($1)
RETURNING id, name, created_at
`

// ============================================================
// ARTISTS
// ============================================================
func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createPlaybackEvent = `-- name: CreatePlaybackEvent :one

INSERT INTO playback_events (track_id, user_session_id)
VALUES ($1, $2)
RETURNING id, track_id, user_id, user_session_id, played_at
`

type CreatePlaybackEventParams struct {
	TrackID       uuid.NullUUID  `json:"track_id"`
	UserSessionID sql.NullString `json:"user_session_id"`
}

// ============================================================
// PLAYBACK EVENTS (analytics)
// ============================================================
func (q *Queries) CreatePlaybackEvent(ctx context.Context, arg CreatePlaybackEventParams) (PlaybackEvent, error) {
	row := q.db.QueryRowContext(ctx, createPlaybackEvent, arg.TrackID, arg.UserSessionID)
	var i PlaybackEvent
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.UserID,
		&i.UserSessionID,
		&i.PlayedAt,
	)
	return i, err
}

const createPreset = `-- name: CreatePreset :one

INSERT INTO presets (name, data, mood, author_id, is_builtin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, data, mood, author_id, is_builtin, created_at
`

type CreatePresetParams struct {
	Name      string         `json:"name"`
	Data      string         `json:"data"`
	Mood      sql.NullString `json:"mood"`
	AuthorID  uuid.NullUUID  `json:"author_id"`
	IsBuiltin bool           `json:"is_builtin"`
}

// ============================================================
// PRESETS
// ============================================================
func (q *Queries) CreatePreset(ctx context.Context, arg CreatePresetParams) (Preset, error) {
	row := q.db.QueryRowContext(ctx, createPreset,
		arg.Name,
		arg.Data,
		arg.Mood,
		arg.AuthorID,
		arg.IsBuiltin,
	)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.Mood,
		&i.AuthorID,
		&i.IsBuiltin,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ============================================================
// REFRESH TOKENS
// ============================================================
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (name)
VALUES ($1)
RETURNING id, name, created_at
`

// ============================================================
// TAGS
// ============================================================
func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTrack = `-- name: CreateTrack :one

INSERT INTO tracks (user_id, title, artist_id, audio_file_path, duration_ms, file_hash, mood, bpm, energy)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, title, artist_id, audio_file_path, duration_ms, file_hash, mood, bpm, energy, created_at, updated_at
`

type CreateTrackParams struct {
	UserID        uuid.UUID       `json:"user_id"`
	Title         string          `json:"title"`
	ArtistID      uuid.NullUUID   `json:"artist_id"`
	AudioFilePath string          `json:"audio_file_path"`
	DurationMs    int32           `json:"duration_ms"`
	FileHash      string          `json:"file_hash"`
	Mood          sql.NullString  `json:"mood"`
	Bpm           sql.NullFloat64 `json:"bpm"`
	Energy        sql.NullFloat64 `json:"energy"`
}

// ============================================================
// TRACKS
// ============================================================
func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, createTrack,
		arg.UserID,
		arg.Title,
		arg.ArtistID,
		arg.AudioFilePath,
		arg.DurationMs,
		arg.FileHash,
		arg.Mood,
		arg.Bpm,
		arg.Energy,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ArtistID,
		&i.AudioFilePath,
		&i.DurationMs,
		&i.FileHash,
		&i.Mood,
		&i.Bpm,
		&i.Energy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUploadSession = `-- name: CreateUploadSession :one

INSERT INTO upload_sessions (status)
VALUES ($1)
RETURNING id, status, track_id, user_id, created_at, updated_at
`

// ============================================================
// UPLOAD SESSIONS
// ============================================================
func (q *Queries) CreateUploadSession(ctx context.Context, status string) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, createUploadSession, status)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TrackID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, display_name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
}

// ============================================================
// USERS
// ============================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artists WHERE id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteArtist, id)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < NOW() OR revoked = TRUE
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens)
	return err
}

const deletePreset = `-- name: DeletePreset :exec
DELETE FROM presets WHERE id = $1 AND author_id = $2
`

type DeletePresetParams struct {
	ID       uuid.UUID     `json:"id"`
	AuthorID uuid.NullUUID `json:"author_id"`
}

func (q *Queries) DeletePreset(ctx context.Context, arg DeletePresetParams) error {
	_, err := q.db.ExecContext(ctx, deletePreset, arg.ID, arg.AuthorID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM tracks WHERE id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTrack, id)
	return err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, created_at FROM artists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtist(ctx context.Context, id uuid.UUID) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtist, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, created_at FROM artists
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getGalleryTracksByUser = `-- name: GetGalleryTracksByUser :many

SELECT
    tr.id             AS track_id,
    tr.title,
    tr.artist_id,
    tr.audio_file_path,
    tr.duration_ms,
    tr.file_hash,
    tr.mood,
    tr.created_at     AS track_created_at,
    tr.updated_at     AS track_updated_at,
    t.id              AS tag_id,
    t.name            AS tag_name,
    t.created_at      AS tag_created_at
FROM tracks tr
INNER JOIN track_tags tt ON tr.id = tt.track_id
INNER JOIN tags t         ON tt.tag_id = t.id
WHERE tr.user_id = $1
ORDER BY t.name ASC, tr.created_at DESC
`

type GetGalleryTracksByUserRow struct {
	TrackID        uuid.UUID      `json:"track_id"`
	Title          string         `json:"title"`
	ArtistID       uuid.NullUUID  `json:"artist_id"`
	AudioFilePath  string         `json:"audio_file_path"`
	DurationMs     int32          `json:"duration_ms"`
	FileHash       string         `json:"file_hash"`
	Mood           sql.NullString `json:"mood"`
	TrackCreatedAt sql.NullTime   `json:"track_created_at"`
	TrackUpdatedAt sql.NullTime   `json:"track_updated_at"`
	TagID          uuid.UUID      `json:"tag_id"`
	TagName        string         `json:"tag_name"`
	TagCreatedAt   sql.NullTime   `json:"tag_created_at"`
}

// ============================================================
// GALLERY (tag-driven grouping, user-scoped)
// ============================================================
func (q *Queries) GetGalleryTracksByUser(ctx context.Context, userID uuid.UUID) ([]GetGalleryTracksByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getGalleryTracksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGalleryTracksByUserRow
	for rows.Next() {
		var i GetGalleryTracksByUserRow
		if err := rows.Scan(
			&i.TrackID,
			&i.Title,
			&i.ArtistID,
			&i.AudioFilePath,
			&i.DurationMs,
			&i.FileHash,
			&i.Mood,
			&i.TrackCreatedAt,
			&i.TrackUpdatedAt,
			&i.TagID,
			&i.TagName,
			&i.TagCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreset = `-- name: GetPreset :one
SELECT id, name, data, mood, author_id, is_builtin, created_at FROM presets WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPreset(ctx context.Context, id uuid.UUID) (Preset, error) {
	row := q.db.QueryRowContext(ctx, getPreset, id)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.Mood,
		&i.AuthorID,
		&i.IsBuiltin,
		&i.CreatedAt,
	)
	return i, err
}

const getPresetFavorite = `-- name: GetPresetFavorite :one
SELECT user_id, preset_id, created_at FROM preset_favorites
WHERE user_id = $1 AND preset_id = $2 LIMIT 1
`

type GetPresetFavoriteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PresetID uuid.UUID `json:"preset_id"`
}

func (q *Queries) GetPresetFavorite(ctx context.Context, arg GetPresetFavoriteParams) (PresetFavorite, error) {
	row := q.db.QueryRowContext(ctx, getPresetFavorite, arg.UserID, arg.PresetID)
	var i PresetFavorite
	err := row.Scan(&i.UserID, &i.PresetID, &i.CreatedAt)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked, created_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked = FALSE AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, name, created_at FROM tags
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT id, user_id, title, artist_id, audio_file_path, duration_ms, file_hash, mood, bpm, energy, created_at, updated_at FROM tracks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTrack(ctx context.Context, id uuid.UUID) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ArtistID,
		&i.AudioFilePath,
		&i.DurationMs,
		&i.FileHash,
		&i.Mood,
		&i.Bpm,
		&i.Energy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackByFileHash = `-- name: GetTrackByFileHash :one
SELECT id, user_id, title, artist_id, audio_file_path, duration_ms, file_hash, mood, bpm, energy, created_at, updated_at FROM tracks
WHERE file_hash = $1 LIMIT 1
`

func (q *Queries) GetTrackByFileHash(ctx context.Context, fileHash string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackByFileHash, fileHash)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ArtistID,
		&i.AudioFilePath,
		&i.DurationMs,
		&i.FileHash,
		&i.Mood,
		&i.Bpm,
		&i.Energy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackByUser = `-- name: GetTrackByUser :one
SELECT id, user_id, title, artist_id, audio_file_path, duration_ms, file_hash, mood, bpm, energy, created_at, updated_at FROM tracks
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetTrackByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTrackByUser(ctx context.Context, arg GetTrackByUserParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackByUser, arg.ID, arg.UserID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ArtistID,
		&i.AudioFilePath,
		&i.DurationMs,
		&i.FileHash,
		&i.Mood,
		&i.Bpm,
		&i.Energy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, status, track_id, user_id, created_at, updated_at FROM upload_sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUploadSession(ctx context.Context, id uuid.UUID) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, getUploadSession, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TrackID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, created_at FROM artists
ORDER BY name ASC
`

func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybackEventsForTrack = `-- name: ListPlaybackEventsForTrack :many
SELECT id, track_id, user_id, user_session_id, played_at FROM playback_events
WHERE track_id = $1
ORDER BY played_at DESC
LIMIT $2
`

type ListPlaybackEventsForTrackParams struct {
	TrackID uuid.NullUUID `json:"track_id"`
	Limit   int32         `json:"limit"`
}

func (q *Queries) ListPlaybackEventsForTrack(ctx context.Context, arg ListPlaybackEventsForTrackParams) ([]PlaybackEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybackEventsForTrack, arg.TrackID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaybackEvent
	for rows.Next() {
		var i PlaybackEvent
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.UserID,
			&i.UserSessionID,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresets = `-- name: ListPresets :many
SELECT id, name, mood, author_id, is_builtin, created_at FROM presets
ORDER BY is_builtin DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListPresetsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPresetsRow struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Mood      sql.NullString `json:"mood"`
	AuthorID  uuid.NullUUID  `json:"author_id"`
	IsBuiltin bool           `json:"is_builtin"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListPresets(ctx context.Context, arg ListPresetsParams) ([]ListPresetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPresets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPresetsRow
	for rows.Next() {
		var i ListPresetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mood,
			&i.AuthorID,
			&i.IsBuiltin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetsByMood = `-- name: ListPresetsByMood :many
SELECT id, name, mood, author_id, is_builtin, created_at FROM presets
WHERE mood = $1
ORDER BY is_builtin DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListPresetsByMoodParams struct {
	Mood   sql.NullString `json:"mood"`
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
}

type ListPresetsByMoodRow struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Mood      sql.NullString `json:"mood"`
	AuthorID  uuid.NullUUID  `json:"author_id"`
	IsBuiltin bool           `json:"is_builtin"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListPresetsByMood(ctx context.Context, arg ListPresetsByMoodParams) ([]ListPresetsByMoodRow, error) {
	rows, err := q.db.QueryContext(ctx, listPresetsByMood, arg.Mood, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPresetsByMoodRow
	for rows.Next() {
		var i ListPresetsByMoodRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mood,
			&i.AuthorID,
			&i.IsBuiltin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTrack = `-- name: ListTagsForTrack :many
SELECT t.id, t.name, t.created_at FROM tags t
INNER JOIN track_tags tt ON t.id = tt.tag_id
WHERE tt.track_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTagsForTrack(ctx context.Context, trackID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithTrackCount = `-- name: ListTagsWithTrackCount :many
SELECT t.id, t.name, t.created_at, count(tt.track_id)::int AS track_count
FROM tags t
LEFT JOIN track_tags tt ON t.id = tt.tag_id
GROUP BY t.id, t.name, t.created_at
ORDER BY track_count DESC, t.name ASC
`

type ListTagsWithTrackCountRow struct {
	ID         uuid.UUID    `json:"id"`
	Name       string       `json:"name"`
	CreatedAt  sql.NullTime `json:"created_at"`
	TrackCount int32        `json:"track_count"`
}

func (q *Queries) ListTagsWithTrackCount(ctx context.Context) ([]ListTagsWithTrackCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithTrackCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsWithTrackCountRow
	for rows.Next() {
		var i ListTagsWithTrackCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackIDsByTag = `-- name: ListTrackIDsByTag :many
SELECT tt.track_id FROM track_tags tt
WHERE tt.tag_id = $1
`

func (q *Queries) ListTrackIDsByTag(ctx context.Context, tagID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listTrackIDsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var track_id uuid.UUID
		if err := rows.Scan(&track_id); err != nil {
			return nil, err
		}
		items = append(items, track_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByTag = `-- name: ListTracksByTag :many
SELECT tr.id, tr.user_id, tr.title, tr.artist_id, tr.audio_file_path, tr.duration_ms, tr.file_hash, tr.mood, tr.bpm, tr.energy, tr.created_at, tr.updated_at FROM tracks tr
INNER JOIN track_tags tt ON tr.id = tt.track_id
WHERE tt.tag_id = $1
ORDER BY tr.created_at DESC
`

func (q *Queries) ListTracksByTag(ctx context.Context, tagID uuid.UUID) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.ArtistID,
			&i.AudioFilePath,
			&i.DurationMs,
			&i.FileHash,
			&i.Mood,
			&i.Bpm,
			&i.Energy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByUser = `-- name: ListTracksByUser :many
SELECT id, user_id, title, artist_id, audio_file_path, duration_ms, file_hash, mood, bpm, energy, created_at, updated_at FROM tracks
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTracksByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTracksByUser(ctx context.Context, arg ListTracksByUserParams) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.ArtistID,
			&i.AudioFilePath,
			&i.DurationMs,
			&i.FileHash,
			&i.Mood,
			&i.Bpm,
			&i.Energy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadSessions = `-- name: ListUploadSessions :many
SELECT id, status, track_id, user_id, created_at, updated_at FROM upload_sessions
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListUploadSessions(ctx context.Context, limit int32) ([]UploadSession, error) {
	rows, err := q.db.QueryContext(ctx, listUploadSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadSession
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TrackID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFavoritePresets = `-- name: ListUserFavoritePresets :many
SELECT p.id, p.name, p.data, p.mood, p.author_id, p.is_builtin, p.created_at FROM presets p
INNER JOIN preset_favorites pf ON p.id = pf.preset_id
WHERE pf.user_id = $1
ORDER BY pf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserFavoritePresetsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserFavoritePresets(ctx context.Context, arg ListUserFavoritePresetsParams) ([]Preset, error) {
	rows, err := q.db.QueryContext(ctx, listUserFavoritePresets, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preset
	for rows.Next() {
		var i Preset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Data,
			&i.Mood,
			&i.AuthorID,
			&i.IsBuiltin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePresetFavorite = `-- name: RemovePresetFavorite :exec
DELETE FROM preset_favorites WHERE user_id = $1 AND preset_id = $2
`

type RemovePresetFavoriteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PresetID uuid.UUID `json:"preset_id"`
}

func (q *Queries) RemovePresetFavorite(ctx context.Context, arg RemovePresetFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removePresetFavorite, arg.UserID, arg.PresetID)
	return err
}

const removeTagFromTrack = `-- name: RemoveTagFromTrack :exec
DELETE FROM track_tags
WHERE track_id = $1 AND tag_id = $2
`

type RemoveTagFromTrackParams struct {
	TrackID uuid.UUID `json:"track_id"`
	TagID   uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromTrack(ctx context.Context, arg RemoveTagFromTrackParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromTrack, arg.TrackID, arg.TagID)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE user_id = $1
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateTrackMood = `-- name: UpdateTrackMood :one
UPDATE tracks
SET mood = $3, bpm = $4, energy = $5, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, artist_id, audio_file_path, duration_ms, file_hash, mood, bpm, energy, created_at, updated_at
`

type UpdateTrackMoodParams struct {
	ID     uuid.UUID       `json:"id"`
	UserID uuid.UUID       `json:"user_id"`
	Mood   sql.NullString  `json:"mood"`
	Bpm    sql.NullFloat64 `json:"bpm"`
	Energy sql.NullFloat64 `json:"energy"`
}

func (q *Queries) UpdateTrackMood(ctx context.Context, arg UpdateTrackMoodParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, updateTrackMood,
		arg.ID,
		arg.UserID,
		arg.Mood,
		arg.Bpm,
		arg.Energy,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ArtistID,
		&i.AudioFilePath,
		&i.DurationMs,
		&i.FileHash,
		&i.Mood,
		&i.Bpm,
		&i.Energy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadSessionStatus = `-- name: UpdateUploadSessionStatus :one
UPDATE upload_sessions
SET status = $2, track_id = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, status, track_id, user_id, created_at, updated_at
`

type UpdateUploadSessionStatusParams struct {
	ID      uuid.UUID     `json:"id"`
	Status  string        `json:"status"`
	TrackID uuid.NullUUID `json:"track_id"`
}

func (q *Queries) UpdateUploadSessionStatus(ctx context.Context, arg UpdateUploadSessionStatusParams) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, updateUploadSessionStatus, arg.ID, arg.Status, arg.TrackID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TrackID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
